import type { InventoryItem } from '@/types'

function id(s: string) {
  return `seed-${s}`
}

function daysAgo(n: number) {
  return Date.now() - n * 86_400_000
}

export const SEED_ITEMS: InventoryItem[] = [
  {
    id: id('milk'),
    name: 'Whole Milk',
    category: 'Dairy',
    quantity: 1,
    minThreshold: 2,
    unit: 'l',
    location: 'fridge',
    notes: undefined,
    imageUrl: undefined,
    createdAt: daysAgo(7),
    updatedAt: daysAgo(1),
  },
  {
    id: id('eggs'),
    name: 'Eggs',
    category: 'Dairy',
    quantity: 4,
    minThreshold: 6,
    unit: 'pcs',
    location: 'fridge',
    notes: 'Free-range',
    imageUrl: undefined,
    createdAt: daysAgo(5),
    updatedAt: daysAgo(2),
  },
  {
    id: id('chicken'),
    name: 'Chicken Breast',
    category: 'Meat & Seafood',
    quantity: 0,
    minThreshold: 1,
    unit: 'kg',
    location: 'freezer',
    notes: undefined,
    imageUrl: undefined,
    createdAt: daysAgo(10),
    updatedAt: daysAgo(3),
  },
  {
    id: id('pasta'),
    name: 'Spaghetti',
    category: 'Pantry',
    quantity: 3,
    minThreshold: 2,
    unit: 'pcs',
    location: 'pantry',
    notes: undefined,
    imageUrl: undefined,
    createdAt: daysAgo(14),
    updatedAt: daysAgo(7),
  },
  {
    id: id('olive-oil'),
    name: 'Olive Oil',
    category: 'Cooking',
    quantity: 1,
    minThreshold: 1,
    unit: 'l',
    location: 'pantry',
    notes: 'Extra virgin',
    imageUrl: undefined,
    createdAt: daysAgo(30),
    updatedAt: daysAgo(5),
  },
  {
    id: id('toothpaste'),
    name: 'Toothpaste',
    category: 'Personal Care',
    quantity: 1,
    minThreshold: 2,
    unit: 'pcs',
    location: 'bathroom',
    notes: undefined,
    imageUrl: undefined,
    createdAt: daysAgo(20),
    updatedAt: daysAgo(10),
  },
  {
    id: id('soap'),
    name: 'Hand Soap',
    category: 'Cleaning',
    quantity: 2,
    minThreshold: 1,
    unit: 'pcs',
    location: 'bathroom',
    notes: undefined,
    imageUrl: undefined,
    createdAt: daysAgo(15),
    updatedAt: daysAgo(8),
  },
  {
    id: id('rice'),
    name: 'Basmati Rice',
    category: 'Pantry',
    quantity: 5,
    minThreshold: 2,
    unit: 'kg',
    location: 'pantry',
    notes: undefined,
    imageUrl: undefined,
    createdAt: daysAgo(60),
    updatedAt: daysAgo(20),
  },
]
